#ifdef __cplusplus
extern "C" {
#endif
	
enum {
	MIXER_RESET = 0x00,
	MIXER_VOL_START = 0x30,
	MIXER_MASTER_LEFT = 0x30,
	MIXER_MASTER_RIGHT,
	MIXER_VOC_LEFT,
	MIXER_VOC_RIGHT,
	MIXER_MIDI_LEFT,
	MIXER_MIDI_RIGHT,
	MIXER_CD_LEFT,
	MIXER_CD_RIGHT,
	MIXER_LINE_LEFT,
	MIXER_LINE_RIGHT,
	MIXER_MIC,
	MIXER_PCSPEAKER,
	MIXER_OUT_SW,
	MIXER_IN_SW_LEFT,
	MIXER_IN_SW_RIGHT,
	MIXER_IN_GAIN_LEFT,
	MIXER_IN_GAIN_RIGHT,
	MIXER_OUT_GAIN_LEFT,
	MIXER_OUT_GAIN_RIGHT,
	MIXER_AGC,
	MIXER_TREBLE_LEFT,
	MIXER_TREBLE_RIGHT,
	MIXER_BASS_LEFT,
	MIXER_BASS_RIGHT,
	MIXER_VOL_END = 0x47
};

void ct1745io_reset(void);
void ct1745io_bind(void);
void ct1745io_unbind(void);


#ifdef __cplusplus
}
#endif
